### ISSUE TITLE
a single pdf file containing all chapters of each book

### ISSUE THREAD

**Issue by vijjo** [suttacentral/editions#7]
In addition to the current paperback versions, please provide single pdf files, containing all chapters of each book, for example, a whole pdf for Middle Length Discourse. Such a file would be useful when used in some apps, such as MarginNote or Liquid Text.

Thank you for the great work!

**Comment by sujato** [comment]
Hi Vijjo,

Thanks for the request, but at this time we won't go ahead with this. Basically, it is *super* complicated to add or combine things in different ways, as it effects all the heading levels, and hence the tables of contents and other things. 

So our focus is on creating one, high quality, and reliable set of files in a consistent way that will cater for the majority of use cases.

Since the source TeX files are available, you're most welcome to use them to create a PDF to your preferences.
